version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-pack
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
