import ProgressBar from '@/utiils/prgoress-bar';
import axios from 'axios';
import Head from 'next/head';
import React, { useState } from 'react';

const PdfToWrod = () => {

    const [files, setFiles] = useState([]);
    const [uid, setUid] = useState("");
    const [loading, setLoading] = useState(false);
    const [progressValue, setProgressValue] = useState(0)


    const handleFileChange = (event) => {
        setFiles(event.target.files);
    };



    const handleDownload = async () => {
        const response = await fetch(`/api/download?uid=${uid}`);
        if (response.ok) {
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${uid}.docx`;
            document.body.appendChild(a);
            a.click();
            a.remove();
        } else {
            console.log("Download failed");
        }
    };


    // File upload
    const handleFileUpload = async (e) => {
        e.preventDefault();
        const formData = new FormData();
        Array.from(files).forEach((file) => {
            formData.append("files", file);
        })
        try {
            setLoading(true)


            const config = {
                headers: {
                    'content-type': 'multipart/form-data',
                },
                onUploadProgress: (progressEvent) => {
                    const loaded = progressEvent.loaded; // Bytes uploaded for current file
                    const total = progressEvent.total; // Total bytes to be uploaded for current file
                    const fileProgress = Math.round((loaded / total) * 100);
                    setProgressValue(fileProgress);
                }
            };

            const { data } = await axios.post("/api/pdf-to-word", formData, config);
            // const response = await fetch("/api/pdf-to-word", {
            //     method: "POST",
            //     body: formData,
            // });
            // const data = await response.json();
            setUid(data.uid)

        } catch (error) {
            console.log(error);
        }
        finally {
            setLoading(false)
        }
    }

    return (
        <>
            <Head>
                <title>Pdf to word</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div style={{ display: 'flex', justifyContent: "center" }}>


                <div style={{ border: "1px solid gray", padding: "10px 40px" }}>
                    <h2>PDF to Word</h2>

                    <form onSubmit={handleFileUpload}>
                        <input
                            type="file"
                            required
                            style={{ marginTop: "50px", border: "1px solid gray", padding: "20px" }}
                            onChange={handleFileChange}
                        />
                        <br />
                        <br />

                        <button style={{ padding: "10px 40px" }} type='submit'>
                            {
                                loading ? "Loading" : "Upload"
                            }
                        </button>
                    </form>

                    {
                        loading && <ProgressBar bgcolor={"#6a1b9a"} completed={progressValue} />
                    }

                    <br />
                    <br />


                    {
                        uid && <div style={{ marginTop: "30px" }}>
                            <input
                                type="text"
                                value={uid}
                                style={{ width: "350px" }}
                                onChange={(e) => setUid(e.target.value)}
                                placeholder="Enter UID"
                            />
                            <button
                                style={{ color: 'green' }}
                                onClick={handleDownload}>
                                Download
                            </button>
                        </div>
                    }

                </div>
            </div>
        </>
    );
};

export default PdfToWrod;